import tkinter.messagebox
from tkinter import *
def F1():
    T2=Toplevel()
    T2.title('LOGIN')
    T2.geometry('500x500')
    T2.configure(bg="light green")
    lbl = Label(T2, text="Login Portal", font="30",bg="light green")
    lbl.pack()
    global e1
    global e2
    f=Frame(T2,bg="light yellow",highlightbackground="black", highlightthickness=1,width=400,height=200)
    f.place(x=50,y=25)
    l1 = Label(T2, text="Student Code",fg="black",bg="light yellow",font="30",width=10)
    l1.place(x=75, y=70)
    l2 = Label(T2, text="Reg.Number",fg="black",bg="light yellow", font="10",width=10)
    l2.place(x=75, y=100)
    l1_value = StringVar
    l2_value = StringVar
    e1 = Entry(T2, textvariable = l1_value)
    e1.place(x=200, y=70)
    e2 = Entry(T2, textvariable = l2_value)
    e2.place(x=200, y=100)
    Button(T2, text="Submit", activebackground="Light Blue", command=F2).place(x=200, y=150)

def F2():
    n1=n2=0
    n1=e1.get()
    n2=e2.get()
    if n1=="arcoaching" and n2=="2729":
        T3=Toplevel()
        T3.title('AR Coaching')
        T3.geometry('1000x1500')
        T3.configure(bg="light green")
        mn = Menu(T3)
        T3.config(menu=mn)
        file_menu = Menu(mn)
        mn.add_cascade(label='Student', menu=file_menu)
        file_menu.add_command(label='New',command=F5)
        file_menu.add_separator()
        file_menu.add_command(label='Exit', command= T3.quit)
        fee_menu = Menu(mn)
        mn.add_cascade(label='Fee and Courses', menu=fee_menu)
        fee_menu.add_command(label='Fee and Courses',command=F3)
        contact_menu = Menu(mn)
        mn.add_cascade(label='Contact', menu=contact_menu)
        contact_menu.add_command(label='Details',command=F7)
        l1=Label(T3,text="AR Coaching Institute",height=3,width=75,highlightbackground="black",highlightthickness=2, font="TIMES 28 bold",bg='lightgreen')
        l1.pack()
        l2=Label(T3,text="Where young minds thrive\nSuccess is the sum of small efforts, repeated day in and day out. It is hard work,\nperseverance, learning, studying, sacrifice and most of all,\nlove of what you are doing or learning to do.\nOne way to keep the momentum going is to constantly have greater goals.\nAR Coaching hereby is your one-step destination for\nlearning and exploring, specialist teaching advice and revision services.\nPERSONALIZED TUTORING FOR SUCCESS!",height=20,width=97,highlightbackground="black",highlightthickness=2, font="CALIBRI 15 bold",bg='lightyellow')
        l2.place(x=8,y=135)
    else:
        T1.title('ERROR')
        tkinter.messagebox.showinfo("Error","Invalid login credentials")

def F3():
    T5=Toplevel()
    T5.title("FEE STRUCTURE AND COURSES")
    T5.geometry('1000x1000')
    T5.configure(bg="light green")
    l1=Label(T5,text="FEE STRUCTURE AND COURSES",height=3,width=75,highlightbackground="black",highlightthickness=2, font="TIMES 28 bold",bg='lightgreen')
    l1.pack()
    f1 = Frame(T5,bg="lightyellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f1.place(x=5,y=135)
    label_f1 = Label(T5,font=("Times",20,'bold'),text="Courses",width=10,fg="Black",bg="lightyellow")
    label_f1.place(x=25,y=138)
    f2 = Frame(T5,bg="lightyellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f2.place(x=250,y=135)
    label_f2 = Label(T5,font=("Times",20,'bold'),text="Course Fee",width=10,fg="Black",bg="lightyellow")
    label_f2.place(x=270,y=138)
    f3 = Frame(T5,bg="lightyellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f3.place(x=495,y=135)
    label_f3 = Label(T5,font=("Times",20,'bold'),text="Course Duration",width=13,fg="Black",bg="lightyellow")
    label_f3.place(x=515,y=138)
    f4 = Frame(T5,bg="yellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f4.place(x=740,y=135)
    label_f4 = Label(T5,font=("Times",20,'bold'),text="Commencement",width=13,fg="Black",bg="yellow")
    label_f4.place(x=760,y=138)
    f5 = Frame(T5, bg="lightyellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f5.place(x=5,y=190)
    label_f5 = Label(T5,font=("Times",18),text="Pre-Nurture",width=10,fg="Black",bg="lightyellow")
    label_f5.place(x=25,y=195)
    f6 = Frame(T5, bg="lightyellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f6.place(x=250,y=190)
    label_f6 = Label(T5,font=("Times",18),text="Rs.1,10,000",width=10,fg="Black",bg="lightyellow")
    label_f6.place(x=270,y=195)
    f7 = Frame(T5, bg="yellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f7.place(x=495,y=190)
    label_f7 = Label(T5,font=("Times",18),text="2yr",width=10,fg="Black",bg="yellow")
    label_f7.place(x=515,y=195)
    f8 = Frame(T5, bg="orange",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f8.place(x=740,y=190)
    label_f8 = Label(T5,font=("Times",18),text="3 April",width=10,fg="Black",bg="orange")
    label_f8.place(x=760,y=195)
    f9 = Frame(T5,bg="lightyellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f9.place(x=5,y=245)
    label_f9 = Label(T5,font=("Times",18),text="Nurture",width=10,fg="Black",bg="lightyellow")
    label_f9.place(x=25,y=250)
    f10 = Frame(T5,bg="yellow",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f10.place(x=250,y=245)
    label_f10 = Label(T5,font=("Times",18),text="Rs.1,29,990",width=10,fg="Black",bg="yellow")
    label_f10.place(x=270,y=250)
    f11 = Frame(T5, bg="orange",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f11.place(x=495,y=245)
    label_f11 = Label(T5,font=("Times",18),text="1yr",width=10,fg="Black",bg="orange")
    label_f11.place(x=515,y=250)
    f12 = Frame(T5,bg="red", highlightbackground="black",highlightthickness=2,width=250,height=50)
    f12.place(x=740,y=245)
    label_f12 = Label(T5,font=("Times",18),text="15 April",width=10,fg="Black",bg="red")
    label_f12.place(x=760,y=250)
    f13 = Frame(T5,bg="yellow", highlightbackground="black",highlightthickness=2,width=250,height=50)
    f13.place(x=5,y=300)
    label_f13 = Label(T5,font=("Times",18),text="Enthuse",width=10,fg="Black",bg="yellow")
    label_f13.place(x=25,y=305)
    f14 = Frame(T5, bg="orange",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f14.place(x=250,y=300)
    label_f14 = Label(T5,font=("Times",18),text="Rs.1,52,000",width=11,fg="Black",bg="orange")
    label_f14.place(x=260,y=305)
    f15 = Frame(T5,bg="red", highlightbackground="black",highlightthickness=2,width=250,height=50)
    f15.place(x=495,y=300)
    label_f15 = Label(T5,font=("Times",18),text="1yr",width=10,fg="Black",bg="red")
    label_f15.place(x=515,y=305)
    f16 = Frame(T5, bg="brown",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f16.place(x=740,y=300)
    label_f16 = Label(T5,font=("Times",18),text="6 April",width=10,fg="black",bg="brown")
    label_f16.place(x=760,y=305)
    f17 = Frame(T5, bg="orange",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f17.place(x=5,y=355)
    label_f17 = Label(T5,font=("Times",18),text="Leader",width=10,fg="Black",bg="orange")
    label_f17.place(x=25,y=360)
    f18 = Frame(T5,bg="red", highlightbackground="black",highlightthickness=2,width=250,height=50)
    f18.place(x=250,y=355)
    label_f17 = Label(T5,font=("Times",18),text="Rs.90,000",width=10,fg="Black",bg="red")
    label_f17.place(x=260,y=360)
    f19 = Frame(T5, bg="brown",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f19.place(x=495,y=355)
    label_f17 = Label(T5,font=("Times",18),text="1yr",width=10,fg="Black",bg="brown")
    label_f17.place(x=515,y=360)
    f20 = Frame(T5, bg="black",highlightbackground="black",highlightthickness=2,width=250,height=50)
    f20.place(x=740,y=355)
    label_f17 = Label(T5,font=("Times",18),text="29 April",width=10,fg="white",bg="black")
    label_f17.place(x=760,y=360)

def F4():
    f1=open("C://Users//HarshaJai//registrations.txt","a")
    s1=e3.get()
    s2=e4.get()
    s3=e5.get()
    s4=e6.get()
    s5=e7.get()
    s6=e8.get()
    s7=e9.get()
    s8=e10.get()
    f1.write(s1+' '+s2+' '+s3+' '+s4+' '+s5+' '+s6+' '+s7+' '+s8+'\n')
    tkinter.messagebox.showinfo("Submitted Successful","Welcome to our venture!")

def F5():
    T6=Toplevel()
    T6.title("My Registration")
    T6.geometry('1500x1500')
    T6.configure(bg='light green')
    l1=Label(T6,text="Full name",height=5,width=20,font="ITCBookmanLight 8 bold",bg="light green")
    l1.grid(row=1,column=2)
    global e3
    global e4
    global e5
    global e6
    global e7
    global e8
    global e9
    global e10
    e3=Entry(T6,bg="light yellow")
    e3.grid(row=1,column=10)
    e4=Entry(T6,bg="light yellow")
    e4.grid(row=1,column=11)
    e5=Entry(T6,bg="light yellow")
    e5.grid(row=1,column=12)
    l2=Label(T6,text="Date of Birth(DD/MM/YYYY)",height=5,width=25,font="ITCBookmanLight 8 bold",bg="light green")
    l2.grid(row=2,column=2)
    e6=Entry(T6,bg="light yellow")
    e6.grid(row=2,column=10)
    l3=Label(T6,text="Age",height=5,width=20,font="ITCBookmanLight 8 bold",bg="light green")
    l3.grid(row=3,column=2)
    e7=Entry(T6,bg="light yellow")
    e7.grid(row=3,column=10)
    l4=Label(T6,text="Gender",height=5,width=20,font="ITCBookmanLight 8 bold",bg="light green")
    l4.grid(row=4,column=2)
    c1=Radiobutton(T6, text='Male',value=1,bg="light yellow")
    c1.grid(row=4,column=10)
    c2=Radiobutton(T6, text='Female',value=2,bg="light yellow")
    c2.grid(row=4,column=11)
    c3=Radiobutton(T6, text='Other',value=3,bg="light yellow")
    c3.grid(row=4,column=12)  
    l5=Label(T6,text="Father's Name",height=5,width=20,font="ITCBookmanLight 8 bold",bg="light green")
    l5.grid(row=5,column=2)
    e8=Entry(T6,bg="light yellow")
    e8.grid(row=5,column=10)
    l6=Label(T6,text="Mother's Name",height=5,width=20,font="ITCBookmanLight 8 bold",bg="light green")
    l6.grid(row=6,column=2)
    e9=Entry(T6,bg="light yellow")
    e9.grid(row=6,column=10)
    l7=Label(T6,text="Contact number",height=5,width=20,font="ITC5BookmanLight 8 bold",bg="light green")
    l7.grid(row=7,column=2)
    e10=Entry(T6,bg="light yellow")
    e10.grid(row=7,column=10)
    b=Button(T6,text="Submit",height=2,width=5,command=F4,bg="light yellow")
    b.grid(row=12,column=10)
    
def F6():
    T6=Toplevel()
    T4.title('AR Coaching') 
    T4.geometry('1000x1500')
    mn = Menu(T4)
    T4.config(menu=mn)
    file_menu = Menu(mn)
    mn.add_cascade(label='Student', menu=file_menu)
    file_menu.add_command(label='New',command=F5)
    file_menu.add_separator()
    file_menu.add_command(label='Exit', command=T4.quit)
    fee_menu = Menu(mn)
    mn.add_cascade(label='Fee and Courses', menu=fee_menu)
    fee_menu.add_command(label='Fee and Courses',command=F3)
    contact_menu = Menu(mn)
    mn.add_cascade(label='Contact', menu=contact_menu)
    contact_menu.add_command(label='Details',command=F7)

def F7():
    T9=Toplevel()
    T9.title('Contact')
    T9.geometry('700x500')
    T9.configure(bg="light green")
    l1=Label(T9,text="AR Coaching Institute",height=3,width=40,highlightbackground="black",highlightthickness=2, font="TIMES 28 bold",bg='lightgreen')
    l1.pack()
    l2=Label(T9,text="For more details:).\nCall-98xxxxxxx7,85xxxxxxx7\nEmail ID-arcoaching@gmail.com",height=10,width=68,highlightbackground="black",highlightthickness=2, font="CALIBRI 15 bold",bg='lightyellow')
    l2.place(x=4,y=135) 

T1=Tk()
T1.title("WELCOME")
T1.geometry('490x300')
T1.configure(bg="light green")
l1=Label(T1,text="WELCOME TO AR COACHING INSTITUTE",height=2,width=38,bg="black",fg="white",font="Algerian 15 bold",highlightbackground="black",highlightthickness=2)
l1.grid(row=4,column=5)
b=Button(T1,text="START",height=2,width=15,font="Albertus 12 bold",bg="light yellow",fg="black",command=F1)
b.grid(row=45,column=5)
T1.mainloop()
